disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- nesting
- cyclomatic_complexity
- function_body_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods


line_length: 200
